import React from 'react'
import { Button } from './Button'
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by Figma Code Connect --
 */

figma.connect(Button, 'https://www.figma.com/design/iJ8gvICLXnbsh9ple9rogK/Design-Systems?node-id=2-5&m=dev', {
  props: {
    label: figma.textContent('Button'), // Matches the text layer named "Button"
  },
  example: ({ label }) => {
    return (
      <Button
        label={label}
        primary={true}
      />
    )
  },
})
