import React from 'react'
import { Toggle } from './Toggle'
import figma from '@figma/code-connect'

/**
 * -- This file was auto-generated by Figma Code Connect --
 */

figma.connect(Toggle, 'https://www.figma.com/design/iJ8gvICLXnbsh9ple9rogK/Design-Systems?node-id=9-13&m=dev', {
  props: {
    checked: figma.boolean('State'),
  },
  example: ({ checked }) => {
    return (
      <Toggle
        checked={checked}
      />
    )
  },
})
